FROM debian:11.6-slim

ENV KEA_VERSION "1.9.0.230131111251"

RUN apt update -qq && apt install -y -qq curl

WORKDIR /usr/local/src/

RUN /usr/bin/curl -1sLfO 'https://dl.cloudsmith.io/public/isc/stork/cfg/setup/bash.deb.sh'
RUN /bin/bash bash.deb.sh
RUN apt install -qq -y isc-stork-server=${KEA_VERSION}

CMD /usr/bin/stork-server
